


# Site settings Update for my Blog : 
title: T.J. Alumbaugh
email: tj.alumbaugh@continuum.io
description: "T.J. Alumbaugh. Can't Stop/Won't Stop Python Developer for Continuum."
baseurl: ""
url: "http://talumbau.github.io"
twitter_username: talumbau
github_username:  talumbau


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: []
  endings: []
  ignore:
    envs: []


kramdown:
  input: GFM
